In [6]:
import requests
import os
from dotenv import load_dotenv
import json
import urllib.request   

load_dotenv()

client_id = os.getenv("NAVER_CLIENT_ID")
client_secret = os.getenv("NAVER_CLIENT_SECRET")

headers = {
    'X-Naver-Client-Id': client_id,
    'X-Naver-Client-Secret': client_secret,
}
shops_list = []
def search_shops(query):
# query string 문자열을 dict 선언
    payload = {
        'query': query,
        'display': 50,
        'sort': 'sim'
    }

    url = 'https://openapi.naver.com/v1/search/shop.json'
    res = requests.get(url, params=payload, headers=headers)
    shops_data = res.json()['items']
    
    shops_dict = {}
    for shop in shops_data:
        shops_dict['제목'] = shop['title']
        shops_dict['링크'] = shop['link']
        shops_dict['사진'] = shop['image']
        shops_dict['최저가'] = shop['lprice']
        shops_dict['최고가'] = shop['hprice']
        shops_dict['쇼핑몰'] = shop['mallName']
        shops_dict['제품번호'] = shop['productId']
        shops_dict['제품종류'] = shop['productType']
        shops_dict['브랜드'] = shop['brand']
        shops_dict['생산'] = shop['maker']
        shops_dict['카테고리1'] = shop['category1']
        shops_dict['카테고리2'] = shop['category2']
        shops_dict['카테고리3'] = shop['category3']
        shops_dict['카테고리4'] = shop['category4']

        shops_list.append(shops_dict)
        shops_dict = {}


    with open('data/shops.json','w',encoding="utf-8")as file:
        for shops in shops_list:
            json.dump(shops, file, ensure_ascii=False, indent=4)

search_shops('가디건건')

In [13]:
import pandas as pd

shops_df = pd.DataFrame(columns=["제목",'링크','사진','최저가','최고가','쇼핑몰','제품번호','제품종류','브랜드','생산','카테고리1','카테고리2','카테고리3','카테고리4'])

for shop_info in shops_list:
    df_new_row = pd.DataFrame.from_records([shop_info])
    shops_df = pd.concat([shops_df, df_new_row])

pd.set_option('display.max_colwidth', 10)
shops_df['최저가'] = pd.to_numeric(shops_df['최저가'], errors='coerce')
shops_df['최고가'] = pd.to_numeric(shops_df['최고가'], errors='coerce')
shops_df.head(5)

,제목,링크,사진,최저가,최고가,쇼핑몰,제품번호,제품종류,브랜드,생산,카테고리1,카테고리2,카테고리3,카테고리4
0,이프네 롤링...,https:...,https:...,21840,NaN,네이버,539412...,1,이프네,패션랜드,패션의류,여성의류,카디건,
0,해피유통 여...,https:...,https:...,17480,NaN,네이버,533551...,1,,,패션의류,여성의류,카디건,
0,털빠짐x 여...,https:...,https:...,29900,NaN,네이버,503027...,1,,,패션의류,여성의류,카디건,
0,캐주얼카디건...,https:...,https:...,37800,NaN,코어나라3,879715...,2,,,패션의류,여성의류,카디건,
0,3D 로즈 ...,https:...,https:...,124000,NaN,쿠팡,540119...,2,,,패션의류,여성의류,카디건,

In [15]:
pd.set_option('display.max_colwidth', 80)
shops_df.loc[shops_df['최저가'] <= 50000, ['브랜드','최저가','쇼핑몰','링크']].sort_values(by='최저가', ascending=True).reset_index(drop=True)

,브랜드,최저가,쇼핑몰,링크
0,,17480,쿠팡,https://link.coupang.com/re/PCSNAVERPCSDP?pageKey=8602028723&ctag=8602028723...
1,,17480,네이버,https://search.shopping.naver.com/catalog/53355123915
2,,17480,쿠팡,https://link.coupang.com/re/PCSNAVERPCSDP?pageKey=8602028723&ctag=8602028723...
3,,17480,쿠팡,https://link.coupang.com/re/PCSNAVERPCSDP?pageKey=8602028723&ctag=8602028723...
4,이프네,21840,더현대닷컴,https://smartstore.naver.com/main/products/11632404903
5,이프네,21840,네이버,https://search.shopping.naver.com/catalog/53941222567
6,이프네,22860,현대Hmall,https://www.hmall.com/md/pda/itemPtc?ReferCode=429&slitmCd=2231183763&utm_so...
7,이프네,23210,더현대닷컴,http://www.thehyundai.com/front/pda/itemPtc.thd?ReferCode=429&utm_source=nav...
8,이프네,24570,현대백화점,https://smartstore.naver.com/main/products/11632131209
9,,25980,GSSHOP,http://with.gsshop.com/alia/aliaGate.gs?media=OB&ecpid=1056254842&vodFlag=N&...
10,,27690,G마켓,https://link.gmarket.co.kr/gate/pcs?item-no=3832455024&sub-id=1003&service-c...
11,,29900,씬나,https://shopping.naver.com/outlink/itemdetail/10834150808
12,,29900,씬나,https://smartstore.naver.com/main/products/10834150809
13,,29900,네이버,https://search.shopping.naver.com/catalog/50302779861
14,,33870,롯데ON,https://www.lotteon.com/p/product/LO2243466001?sitmNo=LO2243466001_224346600...
15,에잇컨셉,33900,마리오아울렛몰,http://www.mariomall.co.kr/Detail?PCode=P002921799&adfrom=naver_ep
16,,34280,아이스탁몰,https://www.istockmall.co.kr/goods/detail/188531?affiliate=naver_Pep
17,,35360,네이버,https://search.shopping.naver.com/catalog/47539890691
18,,35470,길정물산십사번지,https://smartstore.naver.com/main/products/11498960811
19,,37800,코어나라3,https://smartstore.naver.com/main/products/10427020444
20,,43900,파랑새 스마일포,https://smartstore.naver.com/main/products/11680785214
21,,45090,옥션,https://link.auction.co.kr/gate/pcs?item-no=E953139234&sub-id=1&service-code...
22,,45090,G마켓,https://link.gmarket.co.kr/gate/pcs?item-no=4375312256&sub-id=1003&service-c...
23,,47670,11번가,https://www.11st.co.kr/connect/Gateway.tmall?method=Xsite&prdNo=8171603465&t...
24,,47670,11번가,https://www.11st.co.kr/connect/Gateway.tmall?method=Xsite&prdNo=8171603488&t...
25,,48560,11번가,https://www.11st.co.kr/connect/Gateway.tmall?method=Xsite&prdNo=8171629227&t...
26,,48560,11번가,https://www.11st.co.kr/connect/Gateway.tmall?method=Xsite&prdNo=8171629266&t...

In [17]:
pd.set_option('display.max_colwidth', 50)
shops_df.loc[shops_df['쇼핑몰'] == '네이버', '최저가':'브랜드'].sort_values(by='최저가', ascending=True).reset_index(drop=True)

     최저가  최고가  쇼핑몰         제품번호 제품종류  브랜드
0  17480  NaN  네이버  53355123915    1
1  21840  NaN  네이버  53941222567    1  이프네
2  29900  NaN  네이버  50302779861    1
3  35360  NaN  네이버  47539890691    1